name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd functions
          npm install

      - name: Authenticate to GCP
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > ./gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$PWD/gcp-key.json"
          echo "Authenticated to GCP"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Cloud Functions
        run: |
          cd functions
          firebase deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
